"""Draft business reports. Every figure comes from SQL or is quoted from a document (with its source),
never generated by a model. Each report says it is a DRAFT for a responsible person to review.

    accounts     Accounts summary: invoices on file, discrepancies, payables/receivables, bank matching
    aging        Payables and receivables aging with overdue lists
    outstanding  Everything waiting on someone: project tasks, invoice reviews, discrepancies, approvals
    project      Project status: budget vs actual + schedule, tasks, risks and decisions quoted from records

Reports render to Markdown (download) and to self-contained, printable HTML (Print → Save as PDF).
An optional AI-written summary can be added on top; it is labelled as such.
"""

from __future__ import annotations

import html
import re
from dataclasses import dataclass
from datetime import date, datetime
from typing import Any

from app.accounting import analytics
from app.data.store import DataStore


@dataclass
class ReportContext:
    store: DataStore
    documents: list  # ParsedDocument
    approvals: Any
    as_of: date


def _q(store: DataStore, sql: str) -> list[dict[str, Any]]:
    return analytics.query(store, sql, 1000)  # failures are logged and reported at the top of the report


def _money(v: Any) -> str:
    return "-" if v is None else f"${float(v):,.2f}"


def _table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    if not rows:
        return ["_None._", ""]
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c).replace("|", "/") for c in r) + " |" for r in rows]
    return out + [""]


def _header(title: str, ctx: ReportContext) -> list[str]:
    return [f"# {title} (DRAFT)", "",
            f"_Generated {datetime.now().isoformat(timespec='minutes')} from local data, as of {ctx.as_of.isoformat()}. "
            "For review by a responsible person before use._", ""]


# --------------------------------------------------------------------------- legacy summary (API + tests)
def build_summary(store: DataStore) -> dict[str, Any]:
    tables = set(store.tables())
    out: dict[str, Any] = {"generated_at": datetime.now().isoformat(timespec="seconds"), "sections": {}}
    s = out["sections"]
    if "invoices" in tables:
        s["invoices"] = _q(store,
            "SELECT count(*) AS documents, count(*) FILTER (WHERE status = 'needs_review') AS needs_review, "
            "count(*) FILTER (WHERE status = 'approved') AS approved, count(*) FILTER (WHERE issue_count > 0) AS flagged, "
            "round(sum(total) FILTER (WHERE duplicate_of IS NULL AND status <> 'rejected'), 2) AS total_value FROM invoices")
        s["invoices"] = s["invoices"][0] if s["invoices"] else {}
    if "invoice_reconciliation" in tables:
        s["attention"] = _q(store,
            "SELECT status, supplier, invoice_number, document_total, qbo_total, detail FROM invoice_reconciliation "
            "WHERE severity <> 'ok' ORDER BY CASE severity WHEN 'issue' THEN 0 ELSE 1 END, supplier")
    if "qbo_bills" in tables:
        s["payables"] = _q(store,
            "SELECT count(*) FILTER (WHERE balance > 0) AS open_bills, round(sum(balance), 2) AS open_balance FROM qbo_bills")
        s["payables"] = s["payables"][0] if s["payables"] else {}
    if "qbo_invoices" in tables:
        s["receivables"] = _q(store,
            "SELECT count(*) FILTER (WHERE balance > 0) AS open_invoices, round(sum(balance), 2) AS open_balance "
            "FROM qbo_invoices")
        s["receivables"] = s["receivables"][0] if s["receivables"] else {}
    return out


def to_markdown(summary: dict[str, Any]) -> str:
    """Compact markdown for the legacy summary (kept for the QuickBooks tab download)."""
    s = summary["sections"]
    lines = ["# Accounts summary (DRAFT)", "",
             f"_Generated {summary['generated_at']} from local data. For review by a responsible person before use._", ""]
    if "invoices" in s:
        i = s["invoices"]
        lines += ["## Supplier invoices on file",
                  f"- Documents: {i['documents']} ({i['needs_review']} awaiting review, {i['approved']} approved, {i['flagged']} flagged)",
                  f"- Total value (excluding duplicates/rejected): {_money(i['total_value'])}", ""]
    if s.get("attention"):
        lines += ["## Needs attention", ""]
        lines += [f"- **{a['status'].replace('_', ' ')}**: {a['supplier'] or '?'} {a['invoice_number'] or ''} - {a['detail']}"
                  for a in s["attention"]]
        lines.append("")
    if "payables" in s:
        lines += ["## Payables (QuickBooks)", f"- Open bills: {s['payables']['open_bills']} totalling {_money(s['payables']['open_balance'])}", ""]
    if "receivables" in s:
        lines += ["## Receivables (QuickBooks)",
                  f"- Open invoices: {s['receivables']['open_invoices']} totalling {_money(s['receivables']['open_balance'])}", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- document section parsing
_SECTION_WORDS = ("budget", "schedule", "outstanding", "tasks", "actions", "risks", "decisions", "issues", "next steps",
                  "milestones", "summary", "status")


def doc_sections(text: str) -> dict[str, str]:
    """Split a document into {heading: body} using short heading-like lines ('Outstanding tasks', 'Risks')."""
    sections: dict[str, list[str]] = {}
    current = "_intro"
    for raw in text.split("\n"):
        line = re.sub(r"\s{2,}", " ", raw).strip()
        if not line or re.search(r"synthetic data only|page \d+ of \d+", line, re.I):
            continue
        is_heading = (len(line) <= 40 and not re.match(r"^\d", line) and not line.endswith((".", ",", ":"))
                      and any(w in line.lower() for w in _SECTION_WORDS))
        if is_heading:
            current = line
            sections.setdefault(current, [])
        else:
            sections.setdefault(current, []).append(line)
    return {k: "\n".join(v).strip() for k, v in sections.items() if v}


def numbered_items(body: str) -> list[str]:
    items: list[str] = []
    for line in body.split("\n"):
        if re.match(r"^\s*(\d+[.)]|[-•*])\s+", line):
            items.append(re.sub(r"^\s*(\d+[.)]|[-•*])\s+", "", line).strip())
        elif items and line.strip():
            items[-1] += " " + line.strip()
    return items


def project_documents(ctx: ReportContext) -> list:
    return [d for d in ctx.documents if any("outstanding" in k.lower() or k.lower() == "risks" for k in doc_sections(d.text))]


def _find(sections: dict[str, str], *words: str) -> tuple[str, str] | None:
    """Heading that STARTS with one of `words` (in priority order); a document title never matches."""
    for w in words:
        for k, v in sections.items():
            if k.lower().startswith(w):
                return k, v
    return None


_FIGURE = re.compile(r"\b(approved budget|budget|committed(?: to date)?|spent(?: to date)?|actual(?: to date)?)\s*:?\s*"
                     r"\$\s?([\d,]+(?:\.\d{2})?)", re.I)


def document_figures(text: str) -> dict[str, float]:
    """Budget / committed / spent figures stated in a project document."""
    out: dict[str, float] = {}
    for label, value in _FIGURE.findall(text):
        key = "budget" if "budget" in label.lower() else ("committed" if "commit" in label.lower() else "spent")
        out.setdefault(key, float(value.replace(",", "")))
    return out


def _task_flag(task: str, as_of: date) -> str:
    if re.search(r"overdue", task, re.I):
        return "OVERDUE"
    m = re.search(r"due (\d{1,2} \w+ \d{4})", task)
    if m:
        try:
            due = datetime.strptime(m.group(1), "%d %B %Y").date()
            return "OVERDUE" if due < as_of else f"due {due.isoformat()}"
        except ValueError:
            pass
    if re.search(r"not yet|waiting|pending|requested", task, re.I):
        return "waiting"
    return ""


# --------------------------------------------------------------------------- reports
def report_accounts(ctx: ReportContext) -> str:
    st = ctx.store
    out = _header("Accounts summary", ctx)
    inv = analytics.invoice_stats(st)
    if inv:
        out += ["## Supplier invoices on file",
                f"- {inv['documents']} documents: {inv['needs_review']} awaiting review, {inv['approved']} approved, "
                f"{inv['flagged']} flagged; average extraction confidence {inv['avg_confidence']}.", ""]
    rec = _q(st, "SELECT status, supplier, invoice_number, document_total, qbo_total, detail FROM invoice_reconciliation "
                 "WHERE severity <> 'ok' ORDER BY CASE severity WHEN 'issue' THEN 0 ELSE 1 END, supplier") \
        if "invoice_reconciliation" in st.tables() else []
    out += ["## Invoices vs QuickBooks: needs attention", ""]
    out += _table(["Result", "Supplier", "Invoice", "Document", "QuickBooks", "Detail"],
                  [[r["status"].replace("_", " "), r["supplier"] or "?", r["invoice_number"] or "-", _money(r["document_total"]),
                    _money(r["qbo_total"]), r["detail"]] for r in rec])
    bank = _q(st, "SELECT status, date, description, amount, detail FROM bank_reconciliation WHERE severity <> 'ok' "
                  "ORDER BY CASE severity WHEN 'issue' THEN 0 ELSE 1 END, date") if "bank_reconciliation" in st.tables() else []
    out += ["## Bank statement vs QuickBooks: needs attention", ""]
    out += _table(["Result", "Date", "Description", "Amount", "Detail"],
                  [[r["status"].replace("_", " "), r["date"] or "-", r["description"] or "-", _money(r["amount"]), r["detail"]]
                   for r in bank])
    for title, table in (("Payables aging", "qbo_bills"), ("Receivables aging", "qbo_invoices")):
        if table in st.tables():
            ag = analytics.aging(st, table, ctx.as_of)
            out += [f"## {title}", ""] + _table(["Bucket", "Items", "Amount"],
                                                [[b["bucket"], b["count"], _money(b["amount"])] for b in ag])
    return "\n".join(out)


def report_aging(ctx: ReportContext) -> str:
    st = ctx.store
    out = _header("Payables and receivables aging", ctx)
    for title, table, name in (("Payables (bills)", "qbo_bills", "vendor_name"), ("Receivables (customer invoices)",
                                                                                  "qbo_invoices", "customer_name")):
        if table not in st.tables():
            continue
        ag = analytics.aging(st, table, ctx.as_of)
        out += [f"## {title}", ""]
        out += _table(["Bucket", "Items", "Amount"], [[b["bucket"], b["count"], _money(b["amount"])] for b in ag])
        od = analytics.overdue_items(st, table, ctx.as_of, name)
        out += [f"### Overdue {title.split(' ')[0].lower()}", ""]
        out += _table(["Name", "Number", "Due", "Days overdue", "Balance"],
                      [[r["name"], r["doc_number"] or "-", r["due_date"], r["days_overdue"], _money(r["balance"])] for r in od])
    return "\n".join(out)


def report_outstanding(ctx: ReportContext) -> str:
    st = ctx.store
    out = _header("Outstanding items", ctx)
    for d in project_documents(ctx):
        sec = _find(doc_sections(d.text), "outstanding", "actions", "tasks")
        if sec:
            tasks = numbered_items(sec[1])
            out += [f"## Project tasks: {d.file.rsplit('/', 1)[-1]}", ""]
            out += _table(["Task", "Status"], [[t, _task_flag(t, ctx.as_of) or "open"] for t in tasks])
    if "invoices" in st.tables():
        rows = _q(st, "SELECT supplier, invoice_number, total, issue_count, file FROM invoices WHERE status = 'needs_review' "
                      "ORDER BY issue_count DESC, supplier")
        out += ["## Invoices awaiting review", ""]
        out += _table(["Supplier", "Invoice", "Total", "Issues", "File"],
                      [[r["supplier"] or "?", r["invoice_number"] or "MISSING", _money(r["total"]), r["issue_count"],
                        r["file"].rsplit("/", 1)[-1]] for r in rows])
    pending = ctx.approvals.list("pending") if ctx.approvals else []
    out += ["## Actions waiting for approval", ""]
    out += _table(["Action", "Proposed by", "When"], [[p["title"], p["proposed_by"], p["created_at"][:16]] for p in pending])
    od = analytics.overdue_items(st, "qbo_invoices", ctx.as_of, "customer_name")
    out += ["## Customers to chase", ""]
    out += _table(["Customer", "Invoice", "Days overdue", "Balance"],
                  [[r["name"], r["doc_number"], r["days_overdue"], _money(r["balance"])] for r in od])
    return "\n".join(out)


def report_project(ctx: ReportContext) -> str:
    out = _header("Project status", ctx)
    bva = analytics.budget_vs_actual(ctx.store)
    if bva:
        out += ["## Budget vs actual (from project budget spreadsheet)", ""]
        tb = sum(float(r["budget"] or 0) for r in bva)
        ts = sum(float(r["spent"] or 0) for r in bva)
        tc = sum(float(r["committed"] or 0) for r in bva if r.get("committed") is not None)
        out += _table(["Line item", "Budget", "Committed", "Spent", "Spent %"],
                      [[r["item"], _money(r["budget"]), _money(r["committed"]), _money(r["spent"]),
                        f"{100 * float(r['spent'] or 0) / float(r['budget']):.0f}%" if r["budget"] else "-"] for r in bva]
                      + [["**Total**", _money(tb), _money(tc), _money(ts), f"{100 * ts / tb:.0f}%" if tb else "-"]])
        over = [r for r in bva if r.get("committed") is not None and float(r["committed"] or 0) > float(r["budget"] or 0)]
        for r in over:
            out += [f"- **Over budget:** {r['item']} committed {_money(r['committed'])} against a budget of {_money(r['budget'])}."]
        sheet = {"budget": tb, "committed": tc, "spent": ts}
        for d in project_documents(ctx):
            stated = document_figures(d.text)
            for key, val in stated.items():
                if abs(val - sheet[key]) > 0.5:
                    out += [f"- **Discrepancy:** {d.file.rsplit('/', 1)[-1]} states {key} of {_money(val)}, but the budget "
                            f"spreadsheet totals {_money(sheet[key])} (difference {_money(abs(val - sheet[key]))}). "
                            "Check which is current."]
        out.append("")
    for d in project_documents(ctx):
        name = d.file.rsplit("/", 1)[-1]
        sections = doc_sections(d.text)
        out += [f"## From {name}", ""]
        for words, title in ((("budget",), "Budget"), (("schedule", "status"), "Schedule"),
                             (("outstanding", "tasks", "actions"), "Outstanding tasks"), (("risks",), "Risks"),
                             (("decisions",), "Decisions needed")):
            sec = _find(sections, *words)
            if not sec:
                continue
            out += [f"### {title}"]
            items = numbered_items(sec[1])
            if items:
                out += [f"- {t}" + (f" **[{flag}]**" if (flag := _task_flag(t, ctx.as_of)) else "") for t in items]
            else:
                out += [f"> {' '.join(sec[1].split())}"]
            out += [f"_Source: {name}_", ""]
    return "\n".join(out)


REPORTS: dict[str, dict[str, Any]] = {
    "accounts": {"title": "Accounts summary", "description": "Invoices, QuickBooks and bank discrepancies, aging.",
                 "build": report_accounts, "data_class": "accounting"},
    "aging": {"title": "Payables & receivables aging", "description": "Open balances by days overdue, with lists.",
              "build": report_aging, "data_class": "accounting"},
    "outstanding": {"title": "Outstanding items", "description": "Project tasks, invoice reviews, approvals, customers to chase.",
                    "build": report_outstanding, "data_class": "accounting"},
    "project": {"title": "Project status", "description": "Budget vs actual plus schedule, tasks, risks and decisions.",
                "build": report_project, "data_class": "documents"},
}


# --------------------------------------------------------------------------- HTML rendering
def _inline(text: str) -> str:
    t = html.escape(text)
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"(?<![\w])_(.+?)_(?![\w])", r"<em>\1</em>", t)
    return t


def markdown_to_html(md: str, title: str) -> str:
    """Render the (simple, self-generated) report markdown as standalone printable HTML. Escapes all text."""
    body: list[str] = []
    lines = md.split("\n")
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[-|]+\|?$", lines[i + 1]):
            head = [c.strip() for c in ln.strip("|").split("|")]
            body.append("<table><thead><tr>" + "".join(f"<th>{_inline(h)}</th>" for h in head) + "</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                cells = [c.strip() for c in lines[i].strip("|").split("|")]
                body.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in cells) + "</tr>")
                i += 1
            body.append("</tbody></table>")
            continue
        if ln.startswith("### "):
            body.append(f"<h3>{_inline(ln[4:])}</h3>")
        elif ln.startswith("## "):
            body.append(f"<h2>{_inline(ln[3:])}</h2>")
        elif ln.startswith("# "):
            body.append(f"<h1>{_inline(ln[2:])}</h1>")
        elif ln.startswith("- "):
            items = []
            while i < len(lines) and lines[i].startswith("- "):
                items.append(f"<li>{_inline(lines[i][2:])}</li>")
                i += 1
            body.append("<ul>" + "".join(items) + "</ul>")
            continue
        elif ln.startswith("> "):
            body.append(f"<blockquote>{_inline(ln[2:])}</blockquote>")
        elif ln.strip():
            body.append(f"<p>{_inline(ln)}</p>")
        i += 1
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><title>{html.escape(title)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body{{font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;color:#1b1f24;max-width:960px;margin:32px auto;padding:0 16px}}
h1{{font-size:22px}} h2{{font-size:17px;margin-top:28px;border-bottom:1px solid #dfe3e8;padding-bottom:4px}} h3{{font-size:14px}}
table{{border-collapse:collapse;width:100%;margin:8px 0 16px;font-size:13px}} th,td{{border:1px solid #dfe3e8;padding:6px 8px;text-align:left;vertical-align:top}}
th{{background:#f0f2f5}} blockquote{{margin:6px 0;padding:6px 12px;border-left:3px solid #2457d6;background:#f6f7f9}}
em{{color:#5f6b7a}} .ai{{background:#fff4dc;border-radius:8px;padding:10px 14px}}
@media print{{body{{margin:0}} h2{{break-after:avoid}} table{{break-inside:auto}} tr{{break-inside:avoid}}}}
</style></head><body>{''.join(body)}</body></html>"""
